version: '3'
name: bootcamp_n11
services:
  rabbitmq:
    container_name: bootcamp_rabbitmq
    image: rabbitmq:3.10.5-management
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bootcamp_n11

  solr:
    image: solr
    container_name: bootcamp_solr
    ports:
      - "8983:8983"
    networks:
      - bootcamp_n11
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - restaurants

  postgres:
    container_name: bootcamp_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: review
    ports:
      - "5432:5432"
    networks:
      - bootcamp_n11

  mongo:
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - '27017:27017'
    networks:
      - bootcamp_n11
    container_name: bootcamp_mongo
    command: --quiet

networks:
  bootcamp_n11:
    driver: bridge